### ISSUE TITLE
External Antenna

### ISSUE THREAD

**Issue by XXplode** [botletics/SIM7000-LTE-Shield#104]
I am working with the sim7000G and would like to install the project in a metal enclosure, along with the electrical components it's tied in with.  

This will likely require me to move to a different antenna.   On the older sim800 GSM units I could use a small rubber ducky antenna.  Can I still do that with the LTE versions?  Any specifics I need to be aware of?

**Comment by botletics** [comment]
You can use a rubber ducky LTE antenna, but please make sure it's for LTE, not for 2G (GSM). Also, if it's LTE and you want to be able to use 2G on it, it should be a multi-band antenna.
