### ISSUE TITLE
Error with getGSMloc()

### ISSUE THREAD

**Issue by jehannon** [botletics/SIM7000-LTE-Shield#106]
I've tried to use the getGMSloc() function in the Adafruit_FONA lib, but doesn't seem to be working. I went in with direct serial to the 7000G and used the AT+CIPGSMLOC command but get errors for that too. AT+CIPGSMLOC is not documented in the 7000 AT manual. 

Has anyone else tried this?

**Comment by botletics** [comment]
Correct, SIM7000 does not support GSMLOC.
