### ISSUE TITLE
 fona.setNetLED() - does not work

### ISSUE THREAD

**Issue by jhiggason** [botletics/SIM7000-LTE-Shield#113]
fona.setNetLED() currently disables the LED no matter the input.  If it is set to true or false it sends this command disabling the LED:

 FONA> 
---> AT+CNETLIGHT=0
<--- OK

**Comment by botletics** [comment]
You're supposed to enter all the relevant function parameters according to [this documentation](https://github.com/botletics/SIM7000-LTE-Shield/wiki/Library-Functions#fonasetnetled)

**Comment by jhiggason** [comment]
I used your example code from that Doc and it shut it off.
