### ISSUE TITLE
 fona.setNetLED() - does not work

### ISSUE THREAD

**Issue by jhiggason** [botletics/SIM7000-LTE-Shield#114]
fona.setNetLED() currently disables the LED no matter the input. If it is set to true or false it sends this command disabling the LED:

FONA>
---> AT+CNETLIGHT=0
<--- OK

Here at the commands I tried:
fona.setNetLED(true, 2, 1000, 0); 
and
fona.setNetLED(true)
and 
fona.setNetLED(true, 2, 64, 3000); 

All three disable the LED on the radio.  I then have to send the AT command AT+CNETLIGHT=1 to turn it back on.

**Comment by botletics** [comment]
Sorry, for some reason I typed "0" for both cases of true and false in the library. Please see the [updated Adafruit_FONA.cpp file](https://github.com/botletics/SIM7000-LTE-Shield/blob/master/Code/Adafruit_FONA.cpp). Thanks!

**Comment by jhiggason** [comment]
You're my hero.  Thank you!
