### ISSUE TITLE
Trouble connecting to Azure

### ISSUE THREAD

**Issue by HoMPQ** [botletics/SIM7000-LTE-Shield#118]
Hi,

first I want to say thank you for your code, it helped me a lot to start with SIM7000.

Since a week I'm trying to connect to azure via MQTT using the SIM7000 modem.

I'm able to connect via AT+CAOPEN, not setting up the client certificate. After that I'm sending my connect packet but I don't get any data in return. My command order so far is:

`
AT+CACID=0 ->
AT+CSSLCFG="sslversion",0,3 // TLS 1.3 ->
AT+CAOPEN ->
AT+CASEND
`
I guess, without setting up the certificate, an unsecure TCP connection is established which Azure won't accept.

So my questions are:
- how to properly setup the client certificate (which folder do I put it using the QPST EFS Explorer)
- what are the commands to load the certificate (mine do not seem to work: AT+CASSLCFG=0,"cacert","cert.crt")

Thank you,
Andy

**Comment by botletics** [comment]
Hi, please post this non-library related question on the [Botletics forum](https://community.botletics.com/). I'm trying to move a lot of the questions there instead of Github. Thanks!
