### ISSUE TITLE
Current measurement

### ISSUE THREAD

**Issue by mjam9814** [botletics/SIM7000-LTE-Shield#119]
Hey, 

I just wanted to ask how did you measure the current consumptions. As in, which parts of the shield did you probe. I don't have the instruments at home so I need to go to school to do it but I'm not really familiar with the tools. 

A picture of the setup would help but if it's inconvenient for you then writing it up is just fine. 

**And on a side note**, I've managed to get the shield, however, it can take up to 10 minutes to get a fixed location. Is this because of bad coverage in my area or is there any way I could improve this. 

Thanks!

**Comment by botletics** [comment]
Hi, please consider posting this question on the [Botletics community forum](https://community.botletics.com/) instead and I'll answer promptly.
