### ISSUE TITLE
AdafruitIO_MQTT_Demo not working

### ISSUE THREAD

**Issue by mjam9814** [botletics/SIM7000-LTE-Shield#121]
Hey guys, 

So I tried to run the MQTT Demo however in the serial monitor it always seems to stop here (shown in the screenshot below)

![image](https://user-images.githubusercontent.com/49941877/62623762-f7657380-b964-11e9-9c81-20bd983b3ce1.png)

I haven't changed the code at this point and only put in my Adafruit credentials.

I've had the same problem with the IoT_example before and commenting out the temperature sensor lines seemed to work but I've tried to do the same with this code but it's just giving me different errors. 

I was wondering if anyone has had any luck in getting the temperature sensor to work. If not, which lines should I comment out to get it to work without using the temperature sensor?

My setup is the same as in the Instructables (Arduino Uno, SIM7000E (v5), 3.7V LiPo battery)

**Comment by botletics** [comment]
If you comment out lines 155, 246, and 252-253 it will compile just fine.

Also, in the future it would be great if you could post on the [Botletics forum instead](https://community.botletics.com/) for questions like this. Thanks!
