### ISSUE TITLE
Couldn't find FONA

### ISSUE THREAD

**Issue by Virginia2006** [botletics/SIM7000-LTE-Shield#123]
Hi,

The following message "FONA could not be found" is displayed when I run LTE-demo, I bought the SHIELD directly in Botletics. The SIM I am using is from another operator (I cannot use the Hologram SIM) and I have already configured the APN of this operator. Can you help me solve this problem?

**Comment by botletics** [comment]
Please make sure you plug in a 3.7V LiPo battery into the shield and check the connections on pins 10 and 11.

**Comment by Virginia2006** [comment]
After compiling the following message appears,  what
What do I need to verify from pins 10 and 11? I soldered the arduino to the shield
![image](https://user-images.githubusercontent.com/47438397/62659612-780a7c80-b931-11e9-989b-c0318c91a2f9.png)

**Comment by botletics** [comment]
Yes, looks like it compiled fine. I just meant to say that if it's not finding the module, maybe check the solder on pins 10 and 11 and make sure you have power from a battery.

**Comment by botletics** [comment]
Also, please consider posting on the [Botletics forum] (https://community.botletics.com/) instead.

**Comment by Virginia2006** [comment]
Is it necessary to plug in 3.7V LiPo battery into the shield?

**Comment by botletics** [comment]
Yes, definitely.
