### ISSUE TITLE
7000E vs 7000G

### ISSUE THREAD

**Issue by I-Connect** [botletics/SIM7000-LTE-Shield#136]
Hi,

This is not really an issue but I am having a hard time figuring out which module to choose so I was hoping anybody here can help me out.

My device will initially be used in Europe but it might expand also outside Europe.

So now I was wondering if I should use the 7000E or the 7000G. I see no pricing differences so why not always choose the 7000G or am I overlooking something here...?

Thx!

**Comment by botletics** [comment]
The SIM7000G is global but doesn't have the same certifications. The Botletics SIM7000G version board is actually $5 more than the SIM7000E board on Amazon.
