### ISSUE TITLE
SIM7100E GPS PROBLEM

### ISSUE THREAD

**Issue by p00uya** [botletics/SIM7000-LTE-Shield#140]
Hi, im using sim7100e LTE module , i test sms, call, some other application of that they worked correctly , now i wanna using gps at command but it seems not worked for example:
when i execute "at+cgps=1,1 & at+cgpsinfo=10 it should respond fixed position information but in fact returned "+cgps:,,,,,,,,,,,,,,"

**Comment by alimorawej** [comment]
This link might help you.
https://techship.com/faq/basic-gnss-gps-usage-guide-for-simcom-sim7100-sim7500-sim7600-series-cellular-modules/
