### ISSUE TITLE
esp32 with iot example error

### ISSUE THREAD

**Issue by dudemyass** [botletics/SIM7000-LTE-Shield#142]
Hi, I have 2 issues. If i upload your code and use hardware serial the esp32 microcontroller keeps crashing with a critical error. If i // out everything related to the temp sensor (all code) then in compiling i get errors in other areas of the code. such as fona not declared?

**Comment by botletics** [comment]
Please use the [ESP32_LTE_Demo](https://github.com/botletics/SIM7000-LTE-Shield/blob/master/Code/examples/ESP32_LTE_Demo/ESP32_LTE_Demo.ino) and it should compile just fine. I just tried it and it works.
