### ISSUE TITLE
For ESP8266, (3.3V), Am i doing correct ?

### ISSUE THREAD

**Issue by narendok** [botletics/SIM7000-LTE-Shield#148]
Pls, could you pls help me to connect esp with 7000e with logic converter?

Check screenshot :

http://prnt.sc/q2o8d6

are the connection ready for esp8266,   I've deleted 5v (uno 5v), & directly vcc to logic jumper . ?

**Comment by botletics** [comment]
Sorry this is not the place to ask about custom implementations of circuitry, etc.
