### ISSUE TITLE
Adafruit_FONA_LTE does not name a type; did you mean 'Adafruit_FONA_3G

### ISSUE THREAD

**Issue by ibrahim-zebary** [botletics/SIM7000-LTE-Shield#151]
Hello dear Timothy  
i read the issue [#34](https://github.com/botletics/SIM7000-LTE-Shield/issues/36)   and followed your instructions completely  which you mentioned it in [here](https://github.com/botletics/SIM7000-LTE-Shield/wiki/Arduino-IDE-Setup),
But I still get the same issue 
Which is 'Adafruit_FONA_LTE' does not name a type; did you mean 'Adafruit_FONA_3G'?
can you help us to solve this issue we don't have much time left, because our final project depending on it. 
thanks!

**Comment by botletics** [comment]
Please make sure you delete any FONA library that might have been installed previously. If you carefully follow those instructions on that so page everything will compile.
