### ISSUE TITLE
OPERATOR SELECTION

### ISSUE THREAD

**Issue by JGLJGL** [botletics/SIM7000-LTE-Shield#152]
Hi, to select an operator in my country I use AT+COPS. But what if I send the SIM7000 module to another country ? Is there any option to connect automatically to the opertator available in that country? So that anyone (with 0 knowledge) could connect the module (once programed).

**Comment by botletics** [comment]
You have to know what network you will be on because you need to enter the APN.

**Comment by ROSW6341** [comment]
Would the AT+CMCFG command be of use?  Setting the <mode> parameter to 1 would automatically select mobile operator configuration according to ICCID information in SIM card.  Other options are also available.

**Comment by botletics** [comment]
I believe module will automatically try to connect to the best available network in the area based on the SIM card that's inserted and the networks nearby. If you use the AT+CNMP and AT+CMNB commands you can narrow down the type of network it tries to connect to, then use AT+COPS=0 to make it search automatically.
