### ISSUE TITLE
SIM7600E postdata Commands

### ISSUE THREAD

**Issue by Weminem** [botletics/SIM7000-LTE-Shield#154]
Hi, I discovered that my SIM7600E answers the referenced CHTTPSOPSE-Command and all the following like CHTTPSSEND without a space after =
I had to delete the space, otherwise the whole function returns with false and doesn't complete the request.
Does the SIM7000E really answers different with the space?

https://github.com/botletics/SIM7000-LTE-Shield/blob/3a9483374b7ed784023e977e59cd14ef3f54bd2b/Code/Adafruit_FONA.cpp#L1836

**Comment by botletics** [comment]
Sorry, these two modules have different AT commands.

**Comment by Weminem** [comment]
Hi,
that may be. But in the if-instruction before it checks for the SIM7600E, so this cannot work for this module.
