### ISSUE TITLE
ADD CERTIFICATES TO THE CODE

### ISSUE THREAD

**Issue by JGLJGL** [botletics/SIM7000-LTE-Shield#160]
Hi, I need to do https requests (GET,POST). I achieve to do it by AT commands with AT+CSSLCFG="convert",2,"......" and AT+SHSSL=1,"....." , but how to do it in the code(programming)?

**Comment by botletics** [comment]
You can either add a function in the .cpp and .h library files that have those commands coded in, or you can [check out this library](https://github.com/botletics/AT-Command-Library)
