### ISSUE TITLE
TCPconnected Does not work on SIM5320 (FONA 3G)

### ISSUE THREAD

**Issue by OscarVanL** [botletics/SIM7000-LTE-Shield#176]
The function `TCPconnected()` sends AT+CIPSTATUS, which is not a valid SIM5320 command. As a result, this function always returns false.

Unfortunately, Adafruit_MQTT_FONA calls TCPconnected() to check the connection before any MQTT action, meaning it cannot be used with the SIM5320.

I'm unsure what the equivalent SIM5320 AT command is.

I've had a brief look at [SIMCom's 3G MQTT Application notes](http://www.microchip.ua/simcom/WCDMA/APPNOTES/SIMCom_3G_MQTT_Application%20Note_V1.00.pdf) and the [AT Command set](https://cdn-shop.adafruit.com/datasheets/SIMCOM_SIM5320_ATC_EN_V2.02.pdf) but nothing stands out as being equivalent.

If there is no equivalent, maybe just making this function return True on my end would be a sufficient bodge to get this to work.

**Comment by botletics** [comment]
The library doesn't currently support MQTT for the SIM5320 so yes, the commands may not work.
