### ISSUE TITLE
Issue getting GPS coordinates

### ISSUE THREAD

**Issue by meaton23** [botletics/SIM7000-LTE-Shield#179]
I am using the LTE_demo example code. The LTE functions all work as expected but when I try to get GPS coordinates I only get this as an output:
FONA> L
	---> AT+CGNSINF
	<--- +CGNSINF: 1,0,,,,,,,0,,,,,,1,,,,21,,

**Comment by botletics** [comment]
Make sure you enable GPS with 'O' first before using 'L'. It also can take a minute or two to get a fix on location.

**Comment by meaton23** [comment]
I did enable GPS first. Maybe I am just not getting good connection with satellites
