### ISSUE TITLE
Does it work for 5320E ?

### ISSUE THREAD

**Issue by nagaokashi** [botletics/SIM7000-LTE-Shield#18]
It seem that can not enable 3G for 5320E ?

**Comment by botletics** [comment]
Hi there, did you use the "G" command in the LTE_Demo code first to enable GPRS then post with "3"?

Please be more specific and include what code you're using, AT command responses, etc.

**Comment by nagaokashi** [comment]
* GPRS is no longer available in my country (JAPAN).
I took a look into the Adafruit_FONA.cpp, instead of using "AT+CSOCKAUTH" for 3G,  you used "AT+CGAUTH". 
```
// set username/password
	      if (apnusername) {
					char authstring[100] = "AT+CGAUTH=1,1,\"";
					char *strp = authstring + strlen(authstring);
					prog_char_strcpy(strp, (prog_char *)apnusername);
					strp+=prog_char_strlen((prog_char *)apnusername);
......

```

This is my AT command
```
AT+CGSOCKCONT=1,"IP","3g-d-2.ocn.ne.jp"
OK
AT+CSOCKSETPN=1
OK
AT+CSOCKAUTH=1,2,"mobile","mobileid@ocn"
OK
AT+CHTTPSSTART
OK
AT+CHTTPSOPSE="httpbin.org",80,1
ERROR
```
I have no ideal about this error and do not know how to debug.

**Comment by botletics** [comment]
Please try "www.httpbin.org" with the "www" and see if it works.

**Comment by nagaokashi** [comment]
Hi @botletics .
I tried but same result.
```
AT+CGSOCKCONT=1,"IP","3g-d-2.ocn.ne.jp"
OK
AT+CSOCKSETPN=1
OK
AT+CSOCKAUTH=1,2,"mobile","mobileid@ocn"
OK
AT+CHTTPSSTART
OK
AT+CHTTPSOPSE="www.httpbin.org",80,1
ERROR
```

If you have any ideal, please tell me.

**Comment by botletics** [comment]
Sorry, I am not 100% sure what might be wrong because users have reported the code works fine on SIM5320 and the same AT commands run on the SIM7500 as well.

Maybe you could try "www.dweet.io" instead? I know that works for me.

**Comment by botletics** [comment]
Did you get it working?
