### ISSUE TITLE
LTE_Demo/ Arduino Uno / SIM7000C / Couldn't find FONA

### ISSUE THREAD

**Issue by lyx623** [botletics/SIM7000-LTE-Shield#194]
Hi, i want to ask why did i encounter this situation?
	<--- 
Timeout: No response to AT... last ditch attempt.
	---> AT
	<--- 
	---> AT
	<--- 
	---> AT
	<--- 
	---> ATE0
	<--- 
	---> ATE0
	<--- 
Couldn't find FONA

 I am stuck, appreciate your help!

**Comment by botletics** [comment]
Hi, are you using a LiPo battery with proper polarity? (Red wire should be on the left side of the connector when you plug it into the board)

**Comment by lyx623** [comment]
!!!Thanks for your reply.

I think maybe it's because I use the order hardware?

[image: image.png]

Timothy Woo <notifications@github.com> 於 2020年8月6日 週四 下午12:14寫道：

**Comment by lyx623** [comment]
I use DFRobot SIM7000C.
I just saw someone asked a similar question, sorry for wasting your time.
