### ISSUE TITLE
7000A (and 7020G) firmware source?  Hard to FOTA when trying to diag the module...

### ISSUE THREAD

**Issue by cynicaljimbo** [botletics/SIM7000-LTE-Shield#197]
Hi!

So, I saw the firmware upgrade tool and images in this project, and have used them successfully, but a couple of questions- I'm having some issues and want to make sure the f/w is the latest rev.

1. Where did that stuff come from??  I think there may be a newer f/w version, but I sure can't find anything on SimCom's site about such things.
2. I'm also working with a SIM7020G HAT from AliExpress- but there's even less about that module around. Any pointers?
To further complicate things, it appears that the 7020 may only support incremental updates, but the documentation is so god-awful I can't tell for sure.  I also don't see a tool- or any real directions for anything other than FOTA, and that sucks pretty bad too.  Google hasn't been much help.

Thanks- these would be great modules if they were a little more solid.
Jim

**Comment by botletics** [comment]
Please post in [one place](https://community.botletics.com/post/firmware-on-botletics-sim7000-hat-yes-i-saw-the-stuff-on-github-10791515?pid=1314611465), thank you.
