### ISSUE TITLE
Not able to update the firmware

### ISSUE THREAD

**Issue by semorem** [botletics/SIM7000-LTE-Shield#198]
Hello there, i'm trying to update the firmware of my SIM7000E NB-IoT HAT compatible with Raspberry and it keeps stuck in "Waiting switch To Download Mode..." like it shows at the following screenshoot:
![image](https://user-images.githubusercontent.com/70369388/93203342-90fc7880-f754-11ea-996e-99ec0e2881c6.png)
I followed the instructions and load the "1351B08SIM7000E" firmware path as it indicates, but its just stuck in place.

**Comment by Tasosgi** [comment]
The BOOT_CFG pin must be sorted to VVD_EXT before update
