### ISSUE TITLE
How to build and compile custom firmware for SIM7X00

### ISSUE THREAD

**Issue by blazczak** [botletics/SIM7000-LTE-Shield#199]
Hey @botletics, kudos on the product and the repo/support.

I'm looking to write and install custom, low-level firmware for the SIMCOM SIM7X00 series, including the SIM7000 in this board. The goal is not to get involved with the AT interface and deal with the underlying libraries directly to really take advantage of the mobile connection and speeds.

Q: Do you happen to have any docs/jists/libs/soft that explain/facilitate this? Have you tried building and deploying custom firmware on 7X00? I've been looking for related documentation etc. online but found nothing besides AT and simcom support have not been very helpful - last resort I believe you have a longer standing relationship with them that could potentially help learn about that route.

**Comment by botletics** [comment]
Hi there, please check out [this post](https://github.com/botletics/SIM7000-LTE-Shield/issues/39) and check out the [poster's repo](https://github.com/Thalhammer/simcom_dam
