### ISSUE TITLE
MQTT subscribe - SIM7000_MQTT_Demo

### ISSUE THREAD

**Issue by alepiva** [botletics/SIM7000-LTE-Shield#215]
Hi, 
example SIM7000_MQTT_Demo show how subscribing with
fona.MQTT_subscribe(SUB_TOPIC, 1); // Topic name, QoS

but how can I have a callback on this subscription? or even without callback, how to check if some message is arrived?

AT command that is received is..
"+SMSUB: "TOPIC","message""

Thank you.

**Comment by botletics** [comment]
You could have a subloop that keeps reading the buffer until it identifies "+SMSUB:", then extract the message from it.

**Comment by alepiva** [comment]
Thank you for the example.
