### ISSUE TITLE
fona.getGPS() Example mistake?

### ISSUE THREAD

**Issue by alexseuf** [botletics/SIM7000-LTE-Shield#221]
Hello,

in fona.getGPS() Example at https://github.com/botletics/SIM7000-LTE-Shield/wiki/Library-Functions#example-54

line 17 is: 
// if (fona.getGPS(&latitude, &longitude, &speed_kph, &heading, &altitude, &year, &month, &day, &hour, &minute, &second)) {
but should be:
// if (! fona.getGPS(&latitude, &longitude, &speed_kph, &heading, &altitude, &year, &month, &day, &hour, &minute, &second)) {

with actual code you get everytime into the error mesage wihtout having an error.

**Comment by botletics** [comment]
Thanks, fixed it!
