### ISSUE TITLE
SIM7000 PwrKey pulse duration in powerOn() is not adequate, per manufacturer's specifications

### ISSUE THREAD

**Issue by nt7u** [botletics/SIM7000-LTE-Shield#224]
I've had issues with bringing up a SIM7000A board that resulted in a discovery.  The function 
   **Adafruit_FONA::powerOn(uint8_t FONA_PWRKEY)**
results in a 100 ms pulse on the PWRKEY line yet from what is specified in the SimCom documentation (SIM7000 Series Hardware Design V1.07, Page 24 of 69, Figure 10 & Table 8), the **Minimum duration** for that active low level pulse should be at least **1 second (1000 ms)**.

Please update the code to be compliant.

Also note that the Status output, UART, and USB will also not become active for at least 4.5 seconds after the FALLING EDGE of that pulse (leading edge).  This suggests that one might need to wait additional time before trying to interact with the module.  I found that bringing PWRKEY low for 1.2 seconds followed by another 3.8 seconds of waiting worked consistently and reliably for my application.

**Comment by botletics** [comment]
Thanks for catching that! It must've been a typo. I could've sworn it was in right.
