### ISSUE TITLE
invalid conversion from 'const char*' to 'char*' [-fpermissive]

### ISSUE THREAD

**Issue by qingfeng-zhang** [botletics/SIM7000-LTE-Shield#23]
There got error " invalid conversion from 'const char*' to 'char*' [-fpermissive] " when I compiled your examples by  using your latest version 

In member function 'boolean Adafruit_FONA::postData(const char*, const char*, const char*, const char*)'

Adafruit_FONA.cpp error: invalid conversion from 'const char*' to 'char*' [-fpermissive]

   if (! sendCheckReply(body, ok_reply, 10000)) ,
anyone met the problem?

**Comment by botletics** [comment]
What version of the Arduino IDE do you have?

**Comment by per1234** [comment]
Which board do you have selected from the **Tools > Board** menu?

**Comment by qingfeng-zhang** [comment]
ESP32  DEV,   we have used your previous version  without problem  for a few months

**Comment by botletics** [comment]
OK, I just uploaded new files, please try the library again. It compiles fine on ESP32 now.
