### ISSUE TITLE
+CME ERROR: operation not allowed

### ISSUE THREAD

**Issue by amitc1106** [botletics/SIM7000-LTE-Shield#251]
I am not able to connect , on running I am getting following on serial monitor, 

Attempting to open comm with ATs
	---> AT
	<--- ERROR
	---> AT
	<--- OK
	---> AT
	<--- OK
	---> ATE0
	<--- OK
	---> ATE0
	<--- OK
	---> AT+GMR
	<--- Revision:1351B03SIM7000A

OK

	---> AT+CPMS="SM","SM","SM"
	<--- +CPMS: 3,10,3,10,3,10
FONA is OK
Found 	---> AT+GSN
	<--- 865235030116418
Module IMEI: 865235030116418
	---> AT+CFUN=1
	<--- OK
	---> AT+CGDCONT=1,"IP","hologram"
	<--- OK
	---> AT+CIPSHUT
	<--- SHUT OK
	---> AT+SAPBR=0,1
	<--- OK
	---> AT+CGATT=0
	<--- OK
	---> AT+CIPSHUT
	<--- SHUT OK
	---> AT+CGATT=1
	<--- OK
	---> AT+SAPBR=3,1,"CONTYPE","GPRS"
	<--- OK
	---> AT+SAPBR=3,1,"APN","hologram"
	<--- OK
	---> AT+CSTT="hologram"
	<--- OK
	---> AT+SAPBR=1,1
	<--- OK
	---> AT+CIICR
	<--- OK
Enabled data!
Card initialized. 
	---> AT+CAOPEN?
	<--- OK
Connecting to MQTT... 
	---> AT+CMEE=2
	<--- OK
	---> AT+CMEE?
	<--- +CMEE: 2
	---> AT+CACID=1
	<--- +CME ERROR: operation not allowed
Connection failed

**Comment by botletics** [comment]
Are you running the LTE_Demo sketch with mods?

**Comment by amitc1106** [comment]
I am making a data acquisition system for field application. It's not a demo sketch. I run a demo sketch as well for IO however it gives me an error in reading GPS data.

**Comment by amitc1106** [comment]
> Are you running the LTE_Demo sketch with mods?

I run LTE demo sketch, it works fine. However when I run IOT example, We get this error

**Comment by botletics** [comment]
Have you tried posting data via HTTP with the 'G' and '2' options from the menu, just to make sure cellular data on your SIM card works? What SIM are you using?

**Comment by amitc1106** [comment]
I tried posting data with "G" and '2', and I could see it is posted on dweet.io 
I am using Hologram sim .

**Comment by botletics** [comment]
So it looks like you have `#define SSL_FONA 1` in the .h file. Change that to 0 and see if it posts.

**Comment by amitc1106** [comment]
Sorry for my limited knowledge.  which .h file I should look for.

**Comment by botletics** [comment]
It's the Adafruit_FONA.h file in the "Code" folder.

**Comment by amitc1106** [comment]
Thanks, it resolved the issue.
