### ISSUE TITLE
Done LED doesn't illuminate when supplied 4.2V on VBAT

### ISSUE THREAD

**Issue by davegravy** [botletics/SIM7000-LTE-Shield#252]
Everything else on the module is working as expected for me so far (I'm connected to the Rogers LTE-M network)

The "Done" LED doesn't illuminate. I'm powering it with a bench supply capable of 3A output and I've increased the VBAT supply as far as 4.27V. 

I have no Arduino connected, only my PC via USB.

**Comment by botletics** [comment]
If you don't have an actual LiPo battery connected to it, don't worry about the DONE LED.

**Comment by davegravy** [comment]
I'm only worried because I will ultimately have a LiPo connected. 

However I was not supplying anything to the 5V pin, expecting my usb cable to the pc would provide this. When I supply to the 5V pin as well as VBAT the done LED now illuminates.
