### ISSUE TITLE
avr/sleep.h: No such file or directory

### ISSUE THREAD

**Issue by howdoyoudoit** [botletics/SIM7000-LTE-Shield#262]
Hi, i have problems with IoT_example sketch that attached with FONA library. But I can't run the IoT_example coding but for LTE_example it can run. I don't know what's the problem here but it stated that the ' avr/sleep.h: No such file or directory'. I delete the avr header in the Iot_example but the next error shows ' Error compiling for board NodeMCU 1.0 (ESP-12E Module).". I'm clueless right now and I download the avr library from web but it is still errors. Sorry but I'm new in this field and I'm using the ESP8266/nodemcu for the project of Real-Time GPS Tracker. Hope you guys can help me. Thanks

Error with avr define header:
IoT_Example:153:10: fatal error: avr/sleep.h: No such file or directory
  153 | #include <avr/sleep.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
exit status 1
avr/sleep.h: No such file or directory

Error without avr header:
In file included from C:\Users\HP\AppData\Local\Temp\arduino_modified_sketch_71739\IoT_Example.ino:158:
C:\Users\HP\Documents\Arduino\libraries\Adafruit_MCP9808_Library-master/Adafruit_MCP9808.h:20:10: fatal error: Adafruit_BusIO_Register.h: No such file or directory
   20 | #include "Adafruit_BusIO_Register.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

*I have installed the Adafruit MQTT library and some are running fine and some just are not.
*Actually I'm just compile the coding first before upload into the esp8266 thus I'm not upload yet to esp8266 because I wanna check if there's is error or not before upload. But here's the errors.

**Comment by botletics** [comment]
The problem is that the ESP-12 is NOT an AVR microcontroller. You can't use the AVR sleep for the ESP-12.

**Comment by howdoyoudoit** [comment]
so i have just disabled the avr sleep in the coding right?

**Comment by botletics** [comment]
Yes, you should comment all the AVR sleep lines out of the code if you want it to run on the ESP.

**Comment by howdoyoudoit** [comment]
thanks sir!!!
