### ISSUE TITLE
Wiring ESP8266 with SIM7000G

### ISSUE THREAD

**Issue by howdoyoudoit** [botletics/SIM7000-LTE-Shield#265]
Hi, 
Can you help me with the wiring of ESP8266 and SIM7000G?

Because I have some trouble with that and can your provide some details about the wiring?

**Comment by botletics** [comment]
Please see [this portion](https://github.com/botletics/SIM7000-LTE-Shield/wiki/Pinouts#external-host-board-wiring) of the wiki.

**Comment by howdoyoudoit** [comment]
thanks sir!!!
