### ISSUE TITLE
> Hello, I want to use Arduino Due and SIM7000A to send and receive data from/to AWS IoT Core as MQTT. Are there any examples I can look at? So subscribe/publish to a topic. Any help? Thank you!

### ISSUE THREAD

**Issue by jugkrit** [botletics/SIM7000-LTE-Shield#266]
> Hello, I want to use Arduino Due and SIM7000A to send and receive data from/to AWS IoT Core as MQTT. Are there any examples I can look at? So subscribe/publish to a topic. Any help? Thank you!

Also looking for this

_Originally posted by @davegravy in https://github.com/botletics/SIM7000-LTE-Shield/issues/247#issuecomment-845620976_

**Comment by jugkrit** [comment]
I looking for that as well.

**Comment by Phixygamer** [comment]
Also wondering about this the mega i am using now can not poll the sensors and publish the data at the same time

**Comment by DarshanDodal** [comment]
Has anyone achieved it so far?
