### ISSUE TITLE
SIM7000 SSL QPST

### ISSUE THREAD

**Issue by jugkrit** [botletics/SIM7000-LTE-Shield#268]
How did to change port of SIM7000 from Diagnostics port to AT command in QPST?
<img width="691" alt="simcom" src="https://user-images.githubusercontent.com/91239594/135021405-b138d01d-48b3-4418-9334-ff2657a1f6d6.png">

**Comment by jugkrit** [comment]
> Ok, now it detects the port, I was trying to use the AT port instead of Diagnostics port

Hi, How did you change

**Comment by botletics** [comment]
Use a serial terminal like PuTTY to open the "SimTech HS-USB AT Port 9001 (COM 18)" port in your picture above to send AT commands to it.

**Comment by jugkrit** [comment]
I used Putty to send command with SIM7000 already, what command for switch port to AT command in QPST?
I would like to import CA Root Cert to SIM7000, could you suggest.

**Comment by botletics** [comment]
Use the EFS Explorer tool. Please see [this post](https://github.com/botletics/SIM7000-LTE-Shield/issues/156)
