### ISSUE TITLE
fona library

### ISSUE THREAD

**Issue by brownjug** [botletics/SIM7000-LTE-Shield#281]
i have used this library for about 3 years,,,   I am now trying to upload an old working program that was built on the LTE Demo  platform and now I get this "new " problem, on any sketch that use's ADAFRUIT_Fona
code is  for aSIM 7000G
Adafruit_FONA_LTE fona = Adafruit_FONA_LTE();

I keep getting this error when I compile
'Adafruit_FONA_LTE' does not name a type; did you mean 'Adafruit_FONA_3G'?

**Comment by botletics** [comment]
Please see [this page](https://github.com/botletics/SIM7000-LTE-Shield/wiki/Arduino-IDE-Setup#installing-libraries) on how to properly install the library. Please note that you will need to delete any old versions of the FONA library and download the one from GitHub.
