### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by m-menon** [botletics/SIM7000-LTE-Shield#3]
Just wanted to inform you that the link for SIM7000C is broken on this [page](https://github.com/botletics/SIM7000-LTE-Shield/wiki/Board-Versions). It should be

`http://simcomm2m.com/En/module/detail.aspx?id=167`

instead of

`http://m.simcomm2m.com/En/module/detail.aspx?id=167`

**Comment by botletics** [comment]
Ahh yes, thank you so much! They must have changed the page for some reason.
