### ISSUE TITLE
MQTT Publish failed!!

### ISSUE THREAD

**Issue by Bhavikjp** [botletics/SIM7000-LTE-Shield#30]
Hello @botletics 
I have used SIM808 GPS module and successfully sent GPS data to the Azure IoT hub using HTTP protocol. Now I want to perform the same using the MQTT protocol. 
I have used **IoT_Example.ino** code from your library. but I get the publishing error. 
MQTT connection made successfully. 

**Serial monitor view:**

-------------------------------------------------------------------------------------------------------------------
AT+CIPSTART="TCP","test.mosquitto.org","1883" 
<--- OK 
<--- CONNECT OK 
<--- 
> ---> 84 84 3 194 0 15 0 7 68 101 118 105 99 101 49 0 36 97 116 111 122 105 111 116 38 115 101 61 49 53 53 56 53 48 51 57 50 50 38 115 107 110 61 105 111 116 104 117 98 111 119 110 101 114 164 
<--- SEND OK Publishing GPS data: Mydata 
<--- ERROR Failed to publish data! 
---> AT+CIPCLOSE <--- CLOSE OK
-------------------------------------------------------------------------------------------------------------------

**code is :**

`#elif defined(PROTOCOL_MQTT_MYSIGNAL) 
const char* MQTT_SERVER = "test.mosquitto.org"; 
const char* MQTT_SERVERPORT = 1883; 
// Connect to MQTT broker 
if (!fona.TCPconnect(MQTT_SERVER, MQTT_SERVERPORT)) Serial.println(F("Failed to connect to TCP/IP!")); if (!fona.MQTTconnect("MQTT","","","")) Serial.println(F("Failed to connect to MQTT broker!")); 
if (!fona.MQTTpublish("MyTopic", "Mydata")) Serial.println(F("Failed to publish data!"));`

I want to send GPS data to the Azure using MQTT. But, for now, testing purpose, I have used mosquitto server.
**Can you please help me to solve out this issue.**

**Thanks!!**

**Comment by botletics** [comment]
Sorry I don't have SIM808 to test this. The code was mainly for SIM7000 and some of the commands might be different.
