### ISSUE TITLE
can u add support for sim7600 ? :)

### ISSUE THREAD

**Issue by jhonoryza** [botletics/SIM7000-LTE-Shield#31]
can u add support for sim7600 ? the at command is a little bit different :)

**Comment by botletics** [comment]
Sorry I'm just too busy to add this right now. Also, I don't have hardware for it yet so it's kind of hard to test.

**Comment by botletics** [comment]
Actually I forgot that the SIM7500 has the same AT command set as SIM7600 so yes, I guess the library does support SIM7600.
