### ISSUE TITLE
Linux hangs

### ISSUE THREAD

**Issue by JTrotta** [botletics/SIM7000-LTE-Shield#35]
I noticed that new Linux kernels (> 4.x I believe), already have SIM drivers in option.c. 
Did you test it?
It apparently works, but sometimes the whole systems hangs and must be  rebooted.

**Comment by botletics** [comment]
No, I haven't tested it yet, sorry. I'm not a Linux guy :)

**Comment by botletics** [comment]
By the way, have you looked at issue #15? I included a link to a Linux app note SIMCom gave me.
