### ISSUE TITLE
Adafruit_Fona_LTE does not name a type

### ISSUE THREAD

**Issue by aggounix** [botletics/SIM7000-LTE-Shield#36]
I am trying the tutorial on https://www.hackster.io/botletics/real-time-2g-3g-lte-arduino-gps-tracker-iot-dashboard-01d471
when I try to upload the Iot_Example to the arduino I get this error:
Adafruit_FONA_LTE does not name a type
how can I fix this probleme
I am new to arduino

**Comment by botletics** [comment]
That error means you didn't install the right library. It needs to be the one from here. Please [follow these instructions to install](https://github.com/botletics/SIM7000-LTE-Shield/wiki/Arduino-IDE-Setup)

**Comment by keirthsiva** [comment]
@botletics Hi, I'm working with the SIM7000A to send texts to my phone. I have a hologram sim. I have followed the instructions and am using the example code for LTE_Demo, and downloaded the files/libraries from your link above, however I am still getting the error message of: "  'Adafruit_FONA_LTE' does not name a type ". Can you please let me know how I can go about solving this issue. Thanks.

**Comment by botletics** [comment]
Please go to your Arduino libraries folder and delete any library called Adafruit FONA. Then [follow these instructions](https://github.com/botletics/SIM7000-LTE-Shield/wiki/Arduino-IDE-Setup) to install the library on this GitHub repo. Again, don't go to Adafruit's GitHub repo to get the library! It won't compile. You should see the LTE_Demo appear in the examples within Arduino IDE if you installed the right library.
