### ISSUE TITLE
IOT_Example should update

### ISSUE THREAD

**Issue by muzmmilkhan** [botletics/SIM7000-LTE-Shield#4]
sir as you update the IOT_Example on5/2/2018 it's best and now i can push/publish the data on adafruit io
But sir for disply the latitud longituted on Dashboard lat long must be in csv and it should be one feed.
please sir make the lat long in csv for display the lat long on wegit/dashboard .you are the best thanks a lot

**Comment by botletics** [comment]
Hi, thanks for the suggestion! You are definitely right in that I should update the example to provide CSV format for Adafruit IO. In a couple days I'll actually probably be posting a YouTube tutorial on MQTT and Adafruit IO dashboards!

I also just updated the IoT_Example sketch which [you can find here](https://github.com/botletics/SIM7000-LTE-Shield/blob/master/Code/examples/IoT_Example/IoT_Example.ino)
