### ISSUE TITLE
Confused: Can SIM7000 MQTT via NB-IoT

### ISSUE THREAD

**Issue by NicksonYap** [botletics/SIM7000-LTE-Shield#40]
Hi, 

I'd like to transmit GPS location to server.
The requirements is to transmit using "NB-IoT"

This example seems to use MQTT and allows the option to use NB-IoT/Cat-M module
https://github.com/botletics/SIM7000-LTE-Shield/blob/master/Code/examples/IoT_Example/IoT_Example.ino#L105

Is it true that all I need is an NB-IoT enabled SIM card and network
It will then automatically publish to my MQTT Broker somehow?

This module seems to support 2G all the way to LTE, supporting MQTT, FTP & HTTP
How do I know if NB-IoT is really being used?

Thanks!!

**Comment by botletics** [comment]
Yes, you should be able to use NB-IoT to post via MQTT protocol. I would like to clarify that the SIM7000E supports 2G/2.5G/LTE CAT-M/NB-IOT but notice there is no 3G. You can easily tell the network connection info by using the command AT+CPSI?
