### ISSUE TITLE
Firmware update failed

### ISSUE THREAD

**Issue by robertgrochowski** [botletics/SIM7000-LTE-Shield#41]
Hello,

I have installed all the drivers, no unknown devices appear in Windows Device Manager.
I also followed upgrade instructions step by step, checked everything few times but I still can't manage to update due to "ConnectServer failed1, Please repower 1 DUT" error.

![image](https://user-images.githubusercontent.com/43761945/47318530-99250980-d64c-11e8-92a6-72a1e018cc96.png)

Thanks in advance

**Comment by botletics** [comment]
Hi there,

To aid in assisting you, what hardware are you using? Do you have a 3.7V LiPo battery connected? It may be that your device is shutting off when trying to update. Updating firmware requires a lot of power.

**Comment by robertgrochowski** [comment]
Hi,

Thank you for fast reply. To be honest, I use another SIM700E shield (exactly DFRobot Shield NB) but the producer doesn't include information how to upgrade it. Only Your tutorial seems to be suitable. 

I power it from power supply (12v through VIN) and the board works like a charm. 

I have tried also your 2nd tutorial to upgrade it through QPST Tool but unfornatelly I run into difficulties because I couln't select port from the list (the list was empty). I tried to run as administartor, restart my PC and board as well but that didn't help. Do you have any suggestions? 

Thanks in advance.

**Comment by botletics** [comment]
Do you have any sort of indication that the module is turning off during the update process, especially right before it says to repower DUT?

**Comment by botletics** [comment]
Could you show me a screenshot of what device manager looks like before you do the update? Go through literally each entry in device manager that's related to the SIM7000, right click, update driver, and point it to the drivers folder.

**Comment by robertgrochowski** [comment]
Of course, I have done it for every SIM device.

![image](https://user-images.githubusercontent.com/43761945/47325516-730b6380-d664-11e8-9047-2684a9ce15c4.png)

**Comment by botletics** [comment]
Hmm not sure, sorry.

**Comment by lutfisan** [comment]
> 
> 
> No I don't see any, but I managed to go a little bit further in the firmware update process.
> 
> Now it stucks at "waiting switch to download mode..."
> 
> I've noticed that after starting upgrade process, in device manager appear new device called "QHSUSB_BULK"
> ![image](https://user-images.githubusercontent.com/43761945/47325016-4ce4c400-d662-11e8-9e49-fc4db1f0644d.png)

is it solve? i have same problem

**Comment by robertgrochowski** [comment]
Unfortunately, no.

**Comment by royallyovershoot** [comment]
Hey, @robertgrochowski I know it's more than a year late but I encountered the same exact problem with DFRobot and figured out how to fix it. Feel free to PM me since I this is a Botletics chain :)

**Comment by robertgrochowski** [comment]
@royallyovershoot Thanks for letting know. Can you post your solution here? It will help others as well.

**Comment by royallyovershoot** [comment]
Ok, there are two test points on the board (TP1 and TP2) shown on the attached snippet of the schematic. Those need to be shorted together during update, so using a soldering iron you can solder two pin headers and use a shunt to short them when you are updating the firmware and then remove the shunts when you're done with the update. 

It's important to keep in mind that those two pins must be shunted before powering up the board.
I got to 100% but I got an error that it failed to back-up. But everything is working fine. This was included from the hardware design guide: [here](https://simcom.ee/documents/SIM7000x/SIM7000%20Hardware%20Design_V1.05.pdf)
On Page 20  under "Other interface" -> Boot_CFG it explains it. 

![Capture](https://user-images.githubusercontent.com/20677280/68072465-78fa5100-fd5c-11e9-8b56-b29cb5fdf82f.PNG)

**Comment by madatr** [comment]
> Ok, there are two test points on the board (TP1 and TP2) shown on the attached snippet of the schematic. Those need to be shorted together during update, so using a soldering iron you can solder two pin headers and use a shunt to short them when you are updating the firmware and then remove the shunts when you're done with the update.
> 
> It's important to keep in mind that those two pins must be shunted before powering up the board.
> I got to 100% but I got an error that it failed to back-up. But everything is working fine. This was included from the hardware design guide: [here](https://simcom.ee/documents/SIM7000x/SIM7000%20Hardware%20Design_V1.05.pdf)
> On Page 20 under "Other interface" -> Boot_CFG it explains it.
> ![20191102_104149](https://user-images.githubusercontent.com/20677280/68072575-a98eba80-fd5d-11e9-898f-05b37d8b6ddf.jpg)
> 
> ![Capture](https://user-images.githubusercontent.com/20677280/68072465-78fa5100-fd5c-11e9-8b56-b29cb5fdf82f.PNG)
> 
> [I removed the SIM7000 top metal cap]

MAN, YOU ARE A GOD SEND!!!!!
I've been stuck on this for two weeks and was at giving up point.
Thank you for taking up time to share this. 
and shame on manufacturers who don't share crucial information like this.

**Comment by royallyovershoot** [comment]
@madatr Hah, I'm glad that it helped! It was a dick move from the manufacturers but hope you complete your project with ease now :)

**Comment by hasikp1** [comment]
Hi, I have a SIM7000E module bought from aliexpress. It only have 7 pins as output, G-GND,R-RXD,T-TXD,K-PWRKEY,V-VCC,G-GND and S-SLEEP. I tried to update the firmware following the guide provided by @botletics. I also got the "QHSUSB_BULK" in device manager. Does this mean somehow I have to get boot_cfg and VDD_EXT shorted based on steps provided by @royallyovershoot. Is there any other alternatives?

**Comment by madatr** [comment]
well... I can't tell you what to do exactly. The board i'm using has a USB connector provided with necessary hardware to facilitate that, the error/issue I had is that the update software wouldn't be able to switch the board to download mode so I had to force it using @royallyovershoot instructions.
I would recommend that you make sure that your board can communicate with the PC correctly first as the issue might be from that end.
btw, my board does not have the boot_cfg and vdd_ext as well, i just shorted the pins on the chip using a wire and had someone use the software to update it:
<img width="787" alt="Screenshot 2019-11-20 at 06 49 30" src="https://user-images.githubusercontent.com/45605051/69205013-2db8ae80-0b62-11ea-9182-e96011c90803.png">

**Comment by KerryRJ** [comment]
I have a waveshare NBT-IoT hat. I also got stuck at "waiting switch to download mode" and the QHSUSB_BULK device appeared in device manager. I just updated the driver in device manager from https://www.waveshare.com/wiki/File:SIM7X00-Driver.7z and the update process immediately continued.

**Comment by hasikp1** [comment]
@madatr Are you using this module
![HTB17Qx6qYZnBKNjSZFGq6zt3FXaz](https://user-images.githubusercontent.com/48294216/84620173-dbbbe980-aef4-11ea-946d-068bff2c241b.jpg)

**Comment by semorem** [comment]
> I have a waveshare NBT-IoT hat. I also got stuck at "waiting switch to download mode" and the QHSUSB_BULK device appeared in device manager. I just updated the driver in device manager from https://www.waveshare.com/wiki/File:SIM7X00-Driver.7z and the update process immediately continued.

@KerryRJ hello there, i have the same issue that you did with the same hardware, but i already have the lastest dirvers installed. Did you just update the drivers? Did you do it during the firmware's update?

**Comment by KerryRJ** [comment]
I updated the driver during the firmware update.

Kind Regards

Kerry Jones
Owning Member

Info-Overdrive cc
[IO Drive square logo - blue - small]

m. +27(0)612403717
e. kerry@iodrive.co.za<mailto:kerry@iodrive.co.za>
a. F3 Chief Mhlabunzima Rd., Pietermaritzburg, 3201

Website<http://www.iodrive.co.za/>        Email<mailto:kerry@iodrive.co.za>            IM<sip:kerry@iodrive.co.za>

**Comment by semorem** [comment]
Thanks dude! It seems to be working!!!

**Comment by BuiHao1996** [comment]
> Hello,
> 
> I have installed all the drivers, no unknown devices appear in Windows Device Manager.
> I also followed upgrade instructions step by step, checked everything few times but I still can't manage to update due to "ConnectServer failed1, Please repower 1 DUT" error.
> 
> ![image](https://user-images.githubusercontent.com/43761945/47318530-99250980-d64c-11e8-92a6-72a1e018cc96.png)
> 
> Thanks in advance

Could you send me your software to upload SIM 7600CE ?

**Comment by MaffooClock** [comment]
> No I don't see any, but I managed to go a little bit further in the firmware update process.
> 
> Now it stucks at "waiting switch to download mode..."
> 
> I've noticed that after starting upgrade process, in device manager appear new device called "QHSUSB_BULK"
> ![image](https://user-images.githubusercontent.com/43761945/47325016-4ce4c400-d662-11e8-9e49-fc4db1f0644d.png)

When I got to this, I simply installed the driver (from the same folder as all the other drivers), and as soon as it finished, QDL resumed automatically.

**Comment by VeselaHouba** [comment]
I know this thread is closed, but just for reference:
Using waveshare sim7000E

1. Blew off dust of my old Windows Laptop
1. Plugged the module to USB, didn't see any issues with power consumption
1. Installed drivers as described in https://github.com/botletics/SIM7000-LTE-Shield/wiki/USB-Drivers
1. Following upgrade guide https://github.com/botletics/SIM7000-LTE-Shield/wiki/Updating-Firmware
1. Upgrade hanged on something like "Waiting to switch to download mode"
1. Opened device manager, installed latest driver from https://www.waveshare.com/wiki/File:SIM7X00-Driver.7z
1. Update tool picked-up by itself and continued the installation until finish

**Comment by kjm1102** [comment]
More than 2 years after the last post, I might get lucky?
I've got a 7080G with 1951B05sim7080 firmware that doesn't work too well but the downloader wants to load 1951B04sim7080 which is even older.
I'd like to upgrade it to 1951B07sim7080 that runs great in another 7080G but I can't figure out how to copy it from the modem it's in.
So I'm looking for a link to where I might get some 1951B07sim7080 firmware

**Comment by eisaev** [comment]
@kjm1102 Have you tried this?
https://github.com/Xinyuan-LilyGO/LilyGo-T-PCIE/tree/master/update_simxxxx_firmware/1951B08SIM7080

**Comment by kjm1102** [comment]
tnx for the links. I grabbed the 3 files that this wretched flasher I got from waveshare says it needs & copied them to a folder on an E drive to match the byzantine path it needs (there seems to be no way to edit the path) but the usual story, "computer says no". Can you see what I've missed from the attached? I'm new to modem flashing.
![noexist](https://github.com/botletics/SIM7000-LTE-Shield/assets/92007731/1b56f12e-0dc4-461c-9699-e51dee20c9a8)

**Comment by eisaev** [comment]
> tnx for the links. I grabbed the 3 files that this wretched flasher I got from waveshare says it needs & copied them to a folder on an E drive to match the byzantine path it needs (there seems to be no way to edit the path) but the usual story, "computer says no". Can you see what I've missed from the attached? I'm new to modem flashing. ![noexist](https://private-user-images.githubusercontent.com/92007731/293807827-1b56f12e-0dc4-461c-9699-e51dee20c9a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjUxNzcsIm5iZiI6MTcwNDI2NDg3NywicGF0aCI6Ii85MjAwNzczMS8yOTM4MDc4MjctMWI1NmYxMmUtMGRjNC00NjFjLTk2OTktZTUxZGVlMjBjOWE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA2NTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNzBmYjBjNjQ1OTE4Y2JlYWJmMDEyOGM4ZGRjNDQ0MGEzNmZiNTlmZDk3YjkxZDYzODE0ZGYzODYyOGNkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E3oVFp0LmiDc1eoG_Inqj80HvkyyrKUKpkAZovtmJmI)

The flasher expects that there will be more subfolders in the path. Increase the size of the flasher window to see the full path and try to create the required folder structure.

**Comment by kjm1102** [comment]
tnx Evgeniy.  I finally got the firmware folders where the updater tool expects to find them. 
1) At the beginning device manager shows 3 comports:
    SimTech HS-USB AT Port 9205 (COM27)
    SimTech HS-USB Diagnostics 9205 (COM29)
    Simtech HS-USB NMEA 9205 (COM28)
2) The tool starts on com 29, reads the imei & does a few other things then swaps to COM27 
3) There is a USB disconnect & the 3 comports ABOVE vanish to be replaced Qualcom HS-USBQDLoader 9008 (com30)
4) The tool reconnects on COM30 but timesout waiting for prog_firehose_nand.elf which is definitely present in the folder
Any thoughts on what I could try next?
