### ISSUE TITLE
Firmware Versions

### ISSUE THREAD

**Issue by lidraikh** [botletics/SIM7000-LTE-Shield#44]
The firmware folder doesn't have a version for the SIM7000A, do you have any?
I tried to reach out to Simcom without luck.

The modem I have is facing issues sending SMS when connected to Verison network directly, but it can establish a connection over Http.

appreciate your help

**Comment by botletics** [comment]
Yes I have it, but please email me privately. I haven't gotten explicit permission to share it publicly, but they did say I could share it with my "customers"

**Comment by lidraikh** [comment]
thanks for that,
on the same day, I got it from Simcom team.

but unfortunately, the modem still can't send SMS when connected to Verizon network using Verizon SIM card,  which is provisioned for SMS and DATA.
