### ISSUE TITLE
Intermittent PWR issue

### ISSUE THREAD

**Issue by airy52** [botletics/SIM7000-LTE-Shield#45]
The board seems to intermittently reset the power and the PWR LED on your sim7000A board board goes off. I am sometimes able to get the chip to connect to the verizon hologram network and issues the n or 1 command in the LTE_demo example. Sometimes I get ctreg 0,2 which is searching. But eventually the PWR LED resets and I am unable to get any further responses from AT commands until I hit the reset button on the arduino mega 2650 board to establish a connection with it again. When it connects to the network it seems to be pretty stable for a while, until I issue the G command for gprs. It then gets to the SAPBR command, or sometimes as far as this: 
---> AT+SAPBR=1,1
	<--- OK
	---> AT+CIICR
	<--- +PDP: DEACT
But then the power resets and I am stuck unable to get a response again. When I first tried this a week ago I was able to reach the internet once or twice, after many failed attempts. I did not edit any of the code. I'm connected by USB power. The antenna is connected correctly and I have good signal. Any ideas?

**Comment by botletics** [comment]
Sounds like you do not have a 3.7V LiPo battery, which is required. Please try that and it should work like a charm :)
