### ISSUE TITLE
is there support mqtt for sim7500?

### ISSUE THREAD

**Issue by jhonoryza** [botletics/SIM7000-LTE-Shield#48]
there is no at+cipshut at sim7500, so i cant do a tcp connect to mqtt

**Comment by botletics** [comment]
According to the AT command manual there are no MQTT commands for SIM7500.

**Comment by jhonoryza** [comment]
here is the link for mqtt at commands for sim7500 and 7600
https://ufile.io/kg4id

**Comment by jhonoryza** [comment]
you can verify the devices by try a command, at+cmqttstart, if it return ok then it is supported

**Comment by botletics** [comment]
Hmmm interesting. However, I'm way too busy to work on this right now unfortunately. I'm not even pushing out my next product for this yet. :(
