### ISSUE TITLE
esp8266 package 2.4.x?

### ISSUE THREAD

**Issue by supersjimmie** [botletics/SIM7000-LTE-Shield#53]
In the examples I read:

> Go to boards manager and make sure you have 2.3.0 of esp8266 package! 2.4.0+ won't compile

But what is the issue and why doesn't it compile?
I have several projects for my esp8266 modules with the 2.4.x version, so I would rather not create a fully separated environment just to use 2.3.0.

Also, are there any constrains on the version of the arduino ide then?

**Comment by botletics** [comment]
Thanks for bringing this back up. Actually it was something really minor and I went ahead and fixed it. You can find the [new library file here](https://github.com/botletics/SIM7000-LTE-Shield/blob/master/Code/Adafruit_FONA.cpp).

I'll also update the description in the code to get rid of that statement about rolling back to v2.3.0.
