### ISSUE TITLE
Is FONA_RST still needed?

### ISSUE THREAD

**Issue by supersjimmie** [botletics/SIM7000-LTE-Shield#54]
In the examples, there is a  ```  #define FONA_RST 7``` line.
Since the RST should not be used, why not remove the entire usage of it?

I ask this because I bought a hardware variant that does not even have the reset pin available.

**Comment by botletics** [comment]
It's there in case of "emergency" per the hardware design doc. It's great for rebooting the module in case something happens and for things like error handling in long term applications. I'm definitely leaving it in but don't feel obligated to use it.
