### ISSUE TITLE
'Adafruit_FONA_LTE' does not name a type

### ISSUE THREAD

**Issue by keirthsiva** [botletics/SIM7000-LTE-Shield#60]
I am working with the SIM7000A shield with the Arduino UNO. I am trying to send text to my phone using the LTE_DEMO. When compiling it throws me the error: Adafruit_FONA_LTE' does not name a type. I have downloaded the latest libraries for the SIM7000 and am using the example code provided. Please let me know any solution to this issue. Thanks.

**Comment by botletics** [comment]
Please see issue #36
