### ISSUE TITLE
Failed to connect to any network

### ISSUE THREAD

**Issue by frnk94** [botletics/SIM7000-LTE-Shield#69]
The shield seems to be working fine ! But when I try to query Network information it doesn't work
-
![image](https://user-images.githubusercontent.com/11723501/52741895-7a080a00-2fa4-11e9-9277-6a6417bd8ed6.png)
![image](https://user-images.githubusercontent.com/11723501/52741918-8b511680-2fa4-11e9-880e-4ac74074f506.png)
![image](https://user-images.githubusercontent.com/11723501/52741920-8db37080-2fa4-11e9-8bc6-595ee65fc394.png)

**Comment by frnk94** [comment]
Seems like it can read the SIM just fine im located in Canada btw and as you can see im using hologram sim card

**Comment by botletics** [comment]
The Hologram SIM won't work in Canada, sorry. You need Bell's LTE CAT-M SIM card or other compatible SIM.

**Comment by frnk94** [comment]
Alright thanks for quick response can you just point me where its saids hologram won't work in canada or how you knew that was the problem I just want to make sure while im looking for new SIMS that the problem wont happen again. Because on Hologram website they say they covered Canada

![image](https://user-images.githubusercontent.com/11723501/52753130-86e82600-2fc3-11e9-8cba-9d65e526eef4.png)

**Comment by frnk94** [comment]
Also Bell's charge 200$ for their IoT SIMS card... I hate this company ahahah

**Comment by botletics** [comment]
I know because other users have confirmed that it won't work there. Also, I know from Hologram themselves that the SIM doesn't yet support LTE CAT-M in Canada. It covers Canada for 2G, 3G, and 4G LTE but not LTE CAT-M or NB-IoT.

**Comment by frnk94** [comment]
Alright ! Ty for everything Also nice project
