### ISSUE TITLE
Need Raspberry Pi Zero W tutorial

### ISSUE THREAD

**Issue by bestpika** [botletics/SIM7000-LTE-Shield#73]
I try to connect it to UART port and enable UART.
Then I use minicom to test and got offline.

**Comment by botletics** [comment]
Sorry I don't really use Raspberry Pi but there are many examples on how to use UART. The main thing you have to do is:

- Make sure you have a 3.7V LiPo battery connected to the shield
- Pulse pin 6 on the shield LOW to turn on the shield
- Communicate via pins 10/11 on the shield (UART)
