### ISSUE TITLE
Failed to complete HTTP GET...

### ISSUE THREAD

**Issue by aschriewer** [botletics/SIM7000-LTE-Shield#74]
I am trying to use the SIM7XXX_LTE_DEMO sketch to send a simple message via dweet.io. I am connected to the cellular network using a Hologram SIM card. When I try to use "Case 2," the following error is displayed:

FONA> 1
	---> AT+CPSI?
	<--- +CPSI: LTE CAT-M1,Online,311-480,0xD702,55098882,371,EUTRAN-BAND13,5230,3,3,-14,-102,-71,10
	---> AT+COPS?
	<--- +COPS: 0,0,"Verizon Wireless Hologram",7

OK
FONA> 2
	---> AT+HTTPTERM
	<--- OK
	---> AT+HTTPINIT
	<--- OK
	---> AT+HTTPPARA="CID",1
	<--- OK
	---> AT+HTTPPARA="URL","dweet.io/dweet/for/865235030073940?temp=687.57&batt=3600"
	<--- OK
	---> AT+HTTPACTION=0
	<--- OK
HTTP status: 601
Data length: 0
Failed to complete HTTP GET...

Any thoughts/suggestions? When I check https://dweet.io/follow/865235030073940, I do not see the data.

**Comment by botletics** [comment]
You must use the "G" command to enable data before doing HTTP commands.
