### ISSUE TITLE
SIM7000 MQTT AT commands not working ??

### ISSUE THREAD

**Issue by mpablo135** [botletics/SIM7000-LTE-Shield#76]
Hi,
According to SIMCOM "SIM7000_Series_MQTT_Application_notes" from here:
https://www.waveshare.com/w/upload/d/d0/SIM7000_Series_MQTT_Application_Note_V1.00.pdf
Also see the attached file.

There are already MQTT commands available for SIM7000 series modules.
Using these commands as opposed to the MQTT libraries will be much easier as shown in their example.
All of the commands related to MQTT return "ERROR" when i send them.
[SIM7000_Series_MQTT_Application_Note_V1.00.pdf](https://github.com/botletics/SIM7000-LTE-Shield/files/2923720/SIM7000_Series_MQTT_Application_Note_V1.00.pdf)

Why i am not able to use these with my shield?

Thanks

**Comment by botletics** [comment]
They probably only implemented that on certain firmware versions.

**Comment by adam6806** [comment]
@botletics where can we get the firmware files and update tool other than your github? I couldn't find them on simcom's site.

**Comment by botletics** [comment]
Everything is on the tutorial: https://github.com/botletics/SIM7000-LTE-Shield/wiki/Updating-Firmware

**Comment by adam6806** [comment]
@botletics that page just links back to the github. I specifically was asking about where can I find all of these files NOT here. For instance what if they update the firmware again and I don't want to wait for you to upload the files.

**Comment by botletics** [comment]
Then you are free to go contact SIMCom and get it yourself, and they do not post them publicly.

**Comment by SCWhite** [comment]
HI, I'm using sim7000E B07
module crash when "AT+SMCONN" is sent

**Comment by RickGijsberts** [comment]
Probably the module holds an old, not gentle closed connection in memory. Closing this one with “AT+SMDISC” before (re)connecting solved this problem for me.

**Comment by botletics** [comment]
Please see the lastest library files. I have included MQTT commands for SIM7000 as well as a SIM7000_MQTT_Example.

**Comment by Tasosgi** [comment]
Hello, which firmware of SIM7000E has the MQTT commands? I try the 1351B07SIM7000E and 1351B08SIM7000E without luck. The strange thing is that after download the new firmware the module become SIM7000A from SIM7000E.

thanks!

**Comment by dberenguer** [comment]
Hi @Tasosgi, did you get to make the MQTT commands work on your SIM7000E modem? I'm also using firmware version 1351B08SIM7000E, which is the latest firmware for version TX2 of the SIM7000E. Simcom seems to be now providing support only for TX3.

**Comment by Tasosgi** [comment]
I didn't have good lack with firmware update. I bought a new SIM7000E module which had support for mqtt. But at the end I use this library MaJerle/lwgsm and not the native MQTT support.

**Comment by dberenguer** [comment]
I was finally able to make the MQTT commands work with firmware 1351B08SIM7000E. It's simply that I had to connect to the wireless network before trying even the most basic MQTT commands.
