### ISSUE TITLE
Tying to update firmare

### ISSUE THREAD

**Issue by axwell** [botletics/SIM7000-LTE-Shield#80]
Hello, i'm trying to update the firmware but every time software is stuck in the waiting to switch to download mode...

In that time i see qhsusb_bulk is unknown in device manager.
Tried to find a driver but without any luck.

![untitled](https://user-images.githubusercontent.com/7890878/53986705-93c1ea80-4127-11e9-8d72-5fd8b1d8f1c8.png)

**Comment by botletics** [comment]
https://github.com/botletics/SIM7000-LTE-Shield/wiki/USB-Drivers
