### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by carlosmbrenner** [botletics/SIM7000-LTE-Shield#85]
Hi! Im having issues with upgrading the firmware of my modem, i tries to upgrade with qpst, the device restarted but quit working, later i tried to upgrade with QDL and get stuck in "ReadImenAndMeid failed!", the device doesnt show up in the ports of qpst but still on device manager, thanks! regards.

**Comment by botletics** [comment]
What SIM7000 version do you have?
