### ISSUE TITLE
Can't connect MQTT with sim5320E

### ISSUE THREAD

**Issue by NamNamIoT** [botletics/SIM7000-LTE-Shield#86]
Thank you for sharing the library.
I tried connecting MQTT with sim5320E but I found some problems of the hospital. As if you used the old AT commands for sim800L, 800H lines. With sim 5320 there will be a number of different commands with them. I have overcome that problem and connected MQTT well, was able to submit data to the topic but not theersub data from MQTT.
Did you test sim5320 connecting MQTT via GPRS?
Thank you once again for sharing the wonderful library with everyone.

**Comment by botletics** [comment]
No, I have implemented MQTT with SIM5320. It has dedicated MQTT commands for it.
