### ISSUE TITLE
Couldn't find FONA

### ISSUE THREAD

**Issue by mjam9814** [botletics/SIM7000-LTE-Shield#89]
Hey,

So I tried running the LTE Demo Sketch, it compiles properly but when i run the serial monitor, its just outputting random characters and at the end it say 'Couldn't find FONA' as shown in the screenshots below.

![image](https://user-images.githubusercontent.com/49941877/56650116-c456e700-66c9-11e9-9144-ab028439f962.png)

![image](https://user-images.githubusercontent.com/49941877/56650239-f36d5880-66c9-11e9-9818-f11284c90655.png)

I'm using the botletics shield (SIM7000G)  with the arduino uno and the hologram simcard (which has been activated). All the LEDS(the two greens and the blinking blue) are on. I've followed each step so far in the instructables and I've downloaded all the libraries so I'm not sure where I've gone wrong.

**Comment by botletics** [comment]
Please make sure you have the proper baud rate set in the serial monitor (9600) and don't change the LTE_Demo code in any way. It should work.

**Comment by mjam9814** [comment]
The error shown in the screenshots happened when I used the original code and didn't change anything. So I guess I'll try to improve the solder joints and will let you know how it goes.

**Comment by mjam9814** [comment]
So I tried to improve the solder joints as much as I could but it doesn't fix the problem. I have two of your shields (SIM7000G (v6) and SIM7000E (v5)) and the same thing happens to both. Could it be because of the Hologram SIM? I live in Sydney if that makes any difference.

**Comment by botletics** [comment]
Do you see the green "PWR" LED turn on?

Please also check if your LiPo battery polarity is correct. The red wire should be on the left side of the connector when you plug it into the board.

**Comment by mjam9814** [comment]
Yup, the LED turns on and the battery is in the correct polarity.

![image](https://user-images.githubusercontent.com/49941877/56881782-d9a28b80-6aa4-11e9-9cbc-be067b95b31f.png)

**Comment by botletics** [comment]
Try unplugging the USB cable connected to the shield. It might be that you're trying to communicate with it via that USB at the same time the Arduino is trying to talk to it via UART.

**Comment by mjam9814** [comment]
I’ve tried that, but still, its giving me the same error

**Comment by botletics** [comment]
Hmm. Maybe something is wrong with your Arduino? I've never heard of this issue before.

**Comment by mjam9814** [comment]
Yeah i was just trying that out to see if it worked and it did. Using Putty, it seems to responds to the commands

**Comment by botletics** [comment]
Then the issue is likely with the solder joints on pins 10 and 11 or the Arduino itself, or a loose fit of the header pins into the Arduino headers.

**Comment by mjam9814** [comment]
Ok then. I'll try to borrow another arduino from a friend and see it if that works. If not then its probably the connections. Do you happen to sell the shields with the headers already soldered on by any chance?

**Comment by botletics** [comment]
Unfortunately no, they all come unsoldered since some people wire it up with other things and prefer to customize it.

**Comment by mjam9814** [comment]
Am I still able to wire it externally to try and get it to work given that I've already soldered the female headers on?

**Comment by mjam9814** [comment]
Used a different arduino and got it to work. Thanks!
