### ISSUE TITLE
How to connecting to IBM Bluemix mqtt Broker

### ISSUE THREAD

**Issue by muzmmilkhan** [botletics/SIM7000-LTE-Shield#9]
sir good afternoon,
i love your all project and i try all method of Iot_example like
 #define PROTOCOL_HTTP_GET         // Generic
#define PROTOCOL_HTTP_POST        // Generic
#define PROTOCOL_MQTT_AIO         // Adafruit IO
#define PROTOCOL_MQTT_CLOUDMQTT   // CloudMQTT

Now i am Successfully Publish Data to CloudMQTT and i want to use NodeRed UI and  now i can use Gauge,Chart etc but i am Geting Probleam in ploting worldmap in Node red as you Privies Help me a lot so this time also i need your help Last time 

i am using the worldmap in ui iframe which is given - under the menu (top right) - Import - Examples - Worldmap in nodered

The co-ordinate is in node red debug tab and console look like this:
 object topic: "location" 
payload: "1,18.392378,76.593338,284.8" 
qos: 0
 retain: false
 _msgid: "68d05896.c67388"

And in debug tab look :
 location : msg.payload : string[27]
 "0,18.394644,76.592491,224.7"

I want to convert it like this {name:"Art", lat:18.394606, lon:76.592514} to show the maker in world map
Please Help

**Comment by botletics** [comment]
Sorry, this isn't a place to ask questions about how to do things. I provide these resources in my spare time and cannot possibly answer everyone's particular requirements.

**Comment by muzmmilkhan** [comment]
its ok sir i got the answer and sorry for this isssue 
thanks
