### ISSUE TITLE
HTTP GET/POST via NB-IoT 

### ISSUE THREAD

**Issue by wwkv** [botletics/SIM7000-LTE-Shield#90]
Hi!

I'm working on a project where I use NB-IoT to post GPS data to dweet.io. I live in Belgium and after some consideration I bought an IoT SIM card from Orange, a local carrier supporting NB-IoT (LTE CAT-M isn't supported by local carriers as far as I know). After a period of testing my code, I contacted Orange for a different issue. They mentioned I used a NB-IoT capable module but was using 2G instead! 

The code I use is (loosely) based on the LTE_Demo you provided. Is there a change I should make so the module posts to dweet using NB-IoT? 

Kind regards and thanks for supporting.

W.

**Comment by botletics** [comment]
You can use the setPreferredMode(), setPreferredLTEMode(), and setOperatingBand() functions in the commented section after module initialization in LTE_Demo code to force it to operate on only NB-IoT.
