### ISSUE TITLE
STATE: PDP DEACT Connection Failed....Error

### ISSUE THREAD

**Issue by rajendran20** [botletics/SIM7000-LTE-Shield#92]
Hi Does anyone get this error when sending GPS coordinates to adafruit io?

Do you have any advise for me regarding this?

Found 'eeeeem!
---------------------
Latitude: -0.000000
Longitude: 0.000000
Speed: 0.00
Heading: 0.00
Altitude: 0.00
---------------------
 ---> AT+CIPSTATUS
 <--- OK
 <--- STATE: PDP DEACT
Connecting to MQTT... 
 ---> AT+CIPSHUT
 <--- SHUT OK
 ---> AT+CIPMUX=0
 <--- OK
 ---> AT+CIPRXGET=1
 <--- OK
AT+CIPSTART="TCP","io.adafruit.com","1883"
 <--- OK
 <--- STATE: PDP DEACT
Connection failed
Retrying MQTT connection in 5 seconds...
 ---> AT+CIPSTATUS
 <--- OK
 <--- STATE: PDP DEACT
 ---> AT+CIPCLOSE
 <--- ERROR
 ---> AT+CIPSHUT
 <--- SHUT OK
 ---> AT+CIPMUX=0
 <--- OK
 ---> AT+CIPRXGET=1
 <--- OK
AT+CIPSTART="TCP","io.adafruit.com","1883"
 <--- OK
 <--- STATE: PDP DEACT
Connection failed
Retrying MQTT connection in 5 seconds...

**Comment by botletics** [comment]
Make sure your AdafruitIO credentials are correct in the code.
