### ISSUE TITLE
IMEI isnt being found

### ISSUE THREAD

**Issue by Audax56** [botletics/SIM7000-LTE-Shield#93]
![IMEI ERROR](https://user-images.githubusercontent.com/50469556/57495606-f9a02f00-729c-11e9-8aab-51522a1eaf25.PNG)

Im using a Sim7000G, the LTE_DEMO worked but the IoT-Example just gets stuck here every time

**Comment by botletics** [comment]
Please make sure you have a LiPo battery connected with proper polarity.

**Comment by sprice-HE** [comment]
I'm having the same issue with the Sim7000A. The red wire is on the left when the connector is closest to you with the sim card on the left as well. As stated by Audax56, the LTE_DEMO worked great, but the IoT example gets hung up at the IMEI.

**Comment by Audax56** [comment]
Try commenting out lines 202, 205 & 304 in IoT_example. That got it working
for me

**Comment by sprice-HE** [comment]
@Audax56 Thanks!  Commenting out the lines associated with the temp sensor worked.
