### ISSUE TITLE
7000G and USSD

### ISSUE THREAD

**Issue by rbeere** [botletics/SIM7000-LTE-Shield#99]
I have a pice of botletics 7000G shield v6.

Has anyone tried USSD transmission yet? For me it does not work. AT+CREG? gives me 0,5 or 0,1 ... so I should be registered to network correctly.
Trying to send USSD ( AT+CUSD=1,"#111*testtest#" )  always on reports "ERROR".

I heard some rumors that SIMCOM 7000 series does not support USSD ... can this be confirmed ?

**Comment by botletics** [comment]
I do not think SIM7000 supports USSD. If the AT command manual doesn't have the commands listed, chances are it's not supported.
